# 错误处理

## Rust 错误处理概述

Rust 的可靠性：错误处理

- 大部分情况下：在编译时提示错误，并处理
- 错误的分类：
    - 可恢复，例如 文件未找到，可再次尝试
    - 不可恢复，bug，例如 访问的索引超出范围

Rust 没有类似异常的机制

- 可恢复错误：`Result<T，E>`
- 不可恢复：`panic!` 宏

## panic!

处理不可恢复的错误

当 `panic!` 宏执行：

- 你的程序会打印一个错误信息
- 展开（unwind）、清理调用栈（Stack）
- 退出程序

**为应对 panic，展开或中止（abort）调用栈**

1. 默认情况下，当 panic 发生：

- 程序展开调用栈（工作量大）

- Rust 沿着调用栈往回走

- 清理每个遇到的函数中的数据

2. 或立即中止调用栈:

- 不进行清理，直接停止程序

- 内存需要 OS 进行清理

想让二进制文件更小，把设置从“展开”改为“中止”：

在 Cargo.toml 中适当的 profile 部分设置：`panic = 'abort'`

**使用 panic! 产生的回溯信息**

panic! 可能出现在：

- 我们写的代码中

- 我们所依赖的代码中

可通过调用 `panic!` 的函数的回溯信息来定位引起问题的代码

通过设置环境变量 `RUST_BACKTRACE` 可得到回溯信息：`set RUST_BACKTRACE=0`

## Result 与可恢复的错误

**Result 枚举**

```rust
enum Result<T, E> {
	Ok(T),
	Err(E),
}
```

T：操作成功情况下，Ok 变体里返回的数据的类型

E：操作失败情况下，Err 变体里返回的错误的类型

**处理 Result 的一种方式：match 表达式**

和 Option 枚举一样，Result 及其变体也是由 prelude 带入作用域

```rust
use std::fs::File;

fn main() {

    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("Error opening file {:?}", error);
        }
    };
}
```

**匹配不同的错误**

- 上例中使用了很多 match
- match 很有用，但是很原始
- 闭包（closure）。`Result<T，E>`有很多方法
    - 它们接收闭包作为参数
    - 使用match实现
    - 使用这些方法会让代码更简洁

**unwrap**

**unwrap**：**match 表达式的一个快捷方法**：

- 如果 Result 结果是 Ok，返回 Ok 里面的值

- 如果 Result 结果是 Err，调用 panic! 宏

**expect**

expect：和 unwrap 类似，但可指定错误信息

**传播错误**

- 在函数中处理错误
- 将错误返回给调用者

**? 运算符**

? 运算符：传播错误的一种快捷方式

- 如果 Result 是 Ok：Ok 中的值就是表达式的结果，然后继续执行程序

- 如果 Result 是 Err：Err 就是**整个函数**的返回值，就像使用了 return

**? 与 from 函数**

Trait `std::convert:From` 上的 from 函数：用于错误之间的转换

被 ? 所应用的错误，会隐式的被 from 函数处理

当 ? 调用 from函数时：它所接收的错误类型会被转化为当前函数返回类型所定义的错误类型

用于：针对不同错误原因，返回同一种错误类型

**? 运算符只能用于返回 Result 的函数**

**? 运算符与 main 函数**

main 函数返回类型是：()

main 函数的返回类型也可以是：`Result<T,E>`

## 什么时候应该用 panic!

**总体原则**

- 在定义一个可能失败的函数时，优先考虑返回 Result
- 否则就 panic!